# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a846c81a5ed108d01b9d4665053c995a2986e9855e487a9eb2b7cd0cf3d702894349f2c0bbd8ac92d63807be350ceb84362add2d63ba193498162a60c22844b

test:
  secret_key_base: 04114df511a89ff1c49c1abb11f6673c4b0a7d8f583f25064651f439e156b5fe91798fe296cc7a4411c65c84d5e06226f93683e7834c15ab470574d18f53731b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
